//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOpenGate.Models.Planeacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class geneticas
    {
        public int id { get; set; }
        public string clave { get; set; }
        public string sku { get; set; }
        public string wh { get; set; }
        public Nullable<decimal> promedio { get; set; }
        public string geneticafinal { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<decimal> maximo { get; set; }
        public string organizacion { get; set; }
    }
}
