//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOpenGate.Models.Planeacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class hl_transit
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public string receiving_org { get; set; }
        public string shipping_org { get; set; }
        public string item_num { get; set; }
        public Nullable<int> revision { get; set; }
        public string item_description { get; set; }
        public string requisition { get; set; }
        public string order_num { get; set; }
        public Nullable<int> line_num { get; set; }
        public string shipment_num { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<System.DateTime> eta_date { get; set; }
        public Nullable<int> orderlineqty_intransit { get; set; }
        public Nullable<int> qty_from_lot { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string lot_status { get; set; }
        public string carrier { get; set; }
        public string way_bill { get; set; }
        public string vendor { get; set; }
    }
}
