//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOpenGate.Models.Planeacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class onhand
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public string org { get; set; }
        public string item { get; set; }
        public Nullable<int> rev { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public string planner_code { get; set; }
        public string country_of_origin { get; set; }
        public string item_status { get; set; }
        public string uom { get; set; }
        public string subinv { get; set; }
        public string locator { get; set; }
        public string locator_status { get; set; }
        public string lot_number { get; set; }
        public string lot_status { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string lpn { get; set; }
        public Nullable<decimal> frozen_unit_cost { get; set; }
        public Nullable<int> on_hand_qty { get; set; }
        public Nullable<decimal> on_hand_value { get; set; }
        public Nullable<int> reserved_qty { get; set; }
        public Nullable<decimal> reserved_value { get; set; }
        public Nullable<int> available_qty { get; set; }
        public Nullable<decimal> available_value { get; set; }
        public string curr_cd { get; set; }
        public Nullable<decimal> unit_weight { get; set; }
        public string weight_uom { get; set; }
        public Nullable<int> case_quantity { get; set; }
        public Nullable<int> pallet_size { get; set; }
        public string hl_itemlc { get; set; }
        public Nullable<int> case_quantity_lot { get; set; }
    }
}
